### ISSUE TITLE
NullPointerException when transmitting RTS commands

### ISSUE THREAD

**Issue by Flunkyball** [cyrilcc/org.openhab.binding.rflink#22]
Hi,

I recently installed the dev version of your RFLink binding 2.2.0 (https://www.dropbox.com/s/ab7j8dz1m9itqi6/org.openhab.binding.rflink_2.2.0.201801210944.jar?dl=0)

I got the thing defined as follows:
`Bridge rflink:bridge:usb0 [ serialPort="/dev/ttyACM0", baudRate=57600 ] {
    rts	F0F0F0	[ deviceId="F0F0F0" ]
}`

and the item:
`Rollershutter blind_LivingRoom "Blind [%s]"                           {channel="rflink:rts:usb0:F0F0F0:command"}
`

Both, the things, the bridge itself as well as the rts thing are shown displayed as online within PaperUI.

In HabPanel I added a button, linked it to the item and defined the command as "DOWN".
Pressing the button results in no action but in a NullPointerException logged in the openhab.log:

`2018-02-24 17:25:35.001 [WARN ] [g.rflink.handler.RfLinkBridgeHandler] - sendMessage: Raw data = unknown
2018-02-24 17:25:35.007 [ERROR] [nal.common.AbstractInvocationHandler] - An error occurred while calling method 'ThingHandler.handleCommand()' on 'org.openhab.binding.rflink.handler.RfLinkHandler@1fcaa4': null
java.lang.NullPointerException: null
        at org.openhab.binding.rflink.messages.RfLinkBaseMessage.decodeMessage(RfLinkBaseMessage.java:157) [222:org.openhab.binding.rflink:2.2.0.201801210944]
        at org.openhab.binding.rflink.messages.RfLinkRtsMessage.decodeMessage(RfLinkRtsMessage.java:79) [222:org.openhab.binding.rflink:2.2.0.201801210944]
        at org.openhab.binding.rflink.handler.RfLinkBridgeHandler$TransmitQueue.send(RfLinkBridgeHandler.java:79) [222:org.openhab.binding.rflink:2.2.0.201801210944]
        at org.openhab.binding.rflink.handler.RfLinkBridgeHandler$TransmitQueue.enqueue(RfLinkBridgeHandler.java:68) [222:org.openhab.binding.rflink:2.2.0.201801210944]
        at org.openhab.binding.rflink.handler.RfLinkBridgeHandler.sendMessage(RfLinkBridgeHandler.java:165) [222:org.openhab.binding.rflink:2.2.0.201801210944]
        at org.openhab.binding.rflink.handler.RfLinkHandler.handleCommand(RfLinkHandler.java:63) [222:org.openhab.binding.rflink:2.2.0.201801210944]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:?]
        at org.eclipse.smarthome.core.internal.common.AbstractInvocationHandler.invokeDirect(AbstractInvocationHandler.java:153) [109:org.eclipse.smarthome.core:0.10.0.b1]
        at org.eclipse.smarthome.core.internal.common.InvocationHandlerSync.invoke(InvocationHandlerSync.java:59) [109:org.eclipse.smarthome.core:0.10.0.b1]
        at com.sun.proxy.$Proxy131.handleCommand(Unknown Source) [222:org.openhab.binding.rflink:2.2.0.201801210944]
        at org.eclipse.smarthome.core.thing.internal.profiles.ProfileCallbackImpl.handleCommand(ProfileCallbackImpl.java:72) [116:org.eclipse.smarthome.core.thing:0.10.0.b1]
        at org.eclipse.smarthome.core.thing.internal.profiles.SystemDefaultProfile.onCommandFromItem(SystemDefaultProfile.java:49) [116:org.eclipse.smarthome.core.thing:0.10.0.b1]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:?]
        at org.eclipse.smarthome.core.internal.common.AbstractInvocationHandler.invokeDirect(AbstractInvocationHandler.java:153) [109:org.eclipse.smarthome.core:0.10.0.b1]
        at org.eclipse.smarthome.core.internal.common.Invocation.call(Invocation.java:53) [109:org.eclipse.smarthome.core:0.10.0.b1]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:?]
        at java.lang.Thread.run(Thread.java:748) [?:?]
`

Is that error know or is my configuration wrong at some point ?

Cheers,
Ludwig

**Comment by johnjore** [comment]
That version is now old and has been removed (as of 2 minutes ago)

1) Please enable debug logging (see readme.md file) and provide more of the log file to show what is going on next time. Its easier to see what is wrong by including what it was doing up-to the point of crashing, not just the crash itself.

2) your thing file is wrong as you are missing the protocol and the hyphen in both locations..

rts         rts-123456      [ deviceId="RTS-123456" ]

The examples are there for a reason. Cut and paste them and replace the device ID (only)...

**Comment by Flunkyball** [comment]
Thanks for the fast response.
Well, the mistake obviousely was on my side. After correcting the syntax as described it works perfectly.
I read the examples up and down but it did not occur to me that the protocol needs to be used as prefix.

One question is remaining. Somfy rollshuters offer a so called comfort position which should be available by sending "MY" as command just like "UP" or "DOWN". Is that going to be implemented ?

Thanks again for your help !

**Comment by johnjore** [comment]
Hm.... not sure how to make this clearer, from readme.md:

"All receiving devices must have the protocol as part of the device name (rts, x10 and AB400D)."

Feel free to update the readme.md file to make this stand out for others?

The My button functionality needs to be requested from the RfLink developer(s). This binding can't add functionality they have not implemented. When/if it is, let me know what the RFLink command is, and I will try and find a way to add it to the binding.
