### ISSUE TITLE
ALLON Command not recognised

### ISSUE THREAD

**Issue by RestOp** [cyrilcc/org.openhab.binding.rflink#42]
Hello

i get this log in OH 2.4

2019-01-24 12:51:09.941 [DEBUG] [g.rflink.handler.RfLinkBridgeHandler] - Message received: Raw data = 20;32;NewKaku;ID=00076000;SWITCH=1;**CMD=ALLOFF**;, Seq number = 50, Device name = NewKaku, Device ID = 00076000-1, **Command = NULL,** Contact = UNDEF, running against 3 listeners

The **Command = NULL,** but real command is **CMD=ALLOFF**

This is the command to turn off all 4 channels at once. 
How can it be fixed?

Thanks a lot!

**Comment by cartemere** [comment]
Hello.

ALLON and ALLOFF commands are currently NOT implemented in the RfLink
plug-in for openHab (whatever version of the plug-in you use).

This is not a hard work, I can add this in the next days if I found enough
time.
I will come back to you once this is available.

Cartemere

**Comment by RestOp** [comment]
Thanks a lot!
I tried to do it by myself, but i have no expirience in this!

**Comment by seekoman** [comment]
Sorry, I add the lines before. But I compiled the jar based on your master fork in eclipce. Installed in the addon and all other rflink functions as usual but when trying an ALLON button i get the output below.


> 22:27:51.818 [DEBUG] [flink.connector.RfLinkSerialConnector] - <<< 20;03;NewKaku;ID=01beb106;SWITCH=0;C                                                             MD=ALLON;
22:27:51.832 [DEBUG] [ng.rflink.handler.RfLinkBridgeHandler] - Message received: Raw data = 20;03;NewKa                                                             ku;ID=01beb106;SWITCH=0;CMD=ALLON;, Seq number = 3, Device name = NewKaku, Device ID = 01beb106-0, Comm                                                             and = ALLON, Contact = OPEN, running against 15 listeners
22:27:51.835 [DEBUG] [iscovery.RfLinkDeviceDiscoveryService] - Received: bridge: rflink:bridge:bec55be8                                                              message: Raw data = 20;03;NewKaku;ID=01beb106;SWITCH=0;CMD=ALLON;, Seq number = 3, Device name = NewKa                                                             ku, Device ID = 01beb106-0, Command = ALLON, Contact = OPEN
22:27:51.842 [DEBUG] [.binding.rflink.handler.RfLinkHandler] - Message from bridge rflink:bridge:bec55b                                                             e8 from device [NewKaku-01beb106-0] type [RfLinkSwitchMessage] matched
22:27:51.846 [DEBUG] [.binding.rflink.handler.RfLinkHandler] - Update channel: contact, state: OPEN
22:27:51.850 [DEBUG] [.binding.rflink.handler.RfLinkHandler] - Update channel: command, state: ALLON
22:27:51.860 [ERROR] [ome.core.internal.events.EventHandler] - Creation of ESH-Event failed, because on                                                             e of the registered event factories has thrown an exception: Error getting class for simple name: 'AllO                                                             nOffType' using package name 'org.eclipse.smarthome.core.library.types.'.
java.lang.IllegalArgumentException: Error getting class for simple name: 'AllOnOffType' using package n                                                             ame 'org.eclipse.smarthome.core.library.types.'.
        at org.eclipse.smarthome.core.items.events.ItemEventFactory.parseSimpleClassName(ItemEventFacto                                                             ry.java:183) ~[?:?]
        at org.eclipse.smarthome.core.items.events.ItemEventFactory.parseType(ItemEventFactory.java:158                                                             ) ~[?:?]
        at org.eclipse.smarthome.core.items.events.ItemEventFactory.getState(ItemEventFactory.java:136)                                                              ~[?:?]
        at org.eclipse.smarthome.core.items.events.ItemEventFactory.createStateEvent(ItemEventFactory.j                                                             ava:116) ~[?:?]
        at org.eclipse.smarthome.core.items.events.ItemEventFactory.createEventByType(ItemEventFactory.                                                             java:80) ~[?:?]
        at org.eclipse.smarthome.core.events.AbstractEventFactory.createEvent(AbstractEventFactory.java                                                             :51) ~[?:?]
        at org.eclipse.smarthome.core.internal.events.EventHandler.createESHEvent(EventHandler.java:121                                                             ) ~[?:?]
        at org.eclipse.smarthome.core.internal.events.EventHandler.handleEvent(EventHandler.java:95) ~[                                                             ?:?]
        at org.eclipse.smarthome.core.internal.events.EventHandler.handleEvent(EventHandler.java:72) ~[                                                             ?:?]
        at org.eclipse.smarthome.core.internal.events.ThreadedEventHandler.lambda$0(ThreadedEventHandle                                                             r.java:67) ~[?:?]
        at java.lang.Thread.run(Thread.java:748) [?:?]
Caused by: java.lang.ClassNotFoundException: org.eclipse.smarthome.core.library.types.AllOnOffType cann                                                             ot be found by org.eclipse.smarthome.core_0.10.0.oh240
        at org.eclipse.osgi.internal.loader.BundleLoader.findClassInternal(BundleLoader.java:484) ~[?:?                                                             ]
        at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:395) ~[?:?]
        at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:387) ~[?:?]
        at org.eclipse.osgi.internal.loader.ModuleClassLoader.loadClass(ModuleClassLoader.java:150) ~[?                                                             :?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:?]
        at java.lang.Class.forName0(Native Method) ~[?:?]
        at java.lang.Class.forName(Class.java:264) ~[?:?]
        at org.eclipse.smarthome.core.items.events.ItemEventFactory.parseSimpleClassName(ItemEventFacto                                                             ry.java:179) ~[?:?]
        ... 10 more

**Comment by seekoman** [comment]
By unlinking the Command channel the error stooped. And it seams like the link of the command channel is causing the error.
Linking the contact works fine.

**Comment by cartemere** [comment]
Thank you for the logs & the details.
I will check on OpenHab forums how custom types can be handled in the Thing
states.

**Comment by cartemere** [comment]
by looking at the other plugins (ex. for the RfxCom), it seems the states only return standard native State, and not "custom" states.
Therefore, I added a fix to convert the input ALLON & ALLOFF custom types to ON & OFF generic types.

You should be able to map the "command" channel again

**Comment by cartemere** [comment]
Fix is now present on the main branch.
